spring.application.name=felana-backend

# Définit le profil actif par défaut sur "local"
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

server.servlet.context-path=/api

#swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Valeurs par défaut du magasin - à surcharger dans application-local/prod
app.magasin.nom=Felana Friperie & Artisanat
app.magasin.adresse=
app.magasin.telephone=
app.magasin.taux-taxe=0.0
